// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjniieyypsupaqixcnio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqbmlpZXl5cHN1cGFxaXhjbmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MTg2NDIsImV4cCI6MjA0OTQ5NDY0Mn0.Q1S25Fn4rYiLnhFD3josr9_9NwI2wkemXXCV_5N82O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);